#HELP, THIS CODE IS TERRIBLY BROKEN

          /   \
        < O . O >
          =| |=
           / \
           
           
#FIXME
# THERE'S AN ALIEN INVADER SOMEWHERE IN THE CODEBASE AND OUR SYSTEMS CAN'T TERMINATE IT
# BECAUSE ITS TOO ADORABLE, PLEASE COMMENT HIM OR THIS PROGRAM SHALL NEVER RUN!!
